### ISSUE TITLE
AttributeError: 'array.array' object has no attribute 'tostring'

### ISSUE THREAD

**Issue by Tribunny** [snoack/python-goto#35]
```python
File "C:\Users\Tribunny\Desktop\Tuya\venv\lib\site-packages\goto.py", line 184, in with_goto
    _patch_code(func_or_code.__code__),
  File "C:\Users\Tribunny\Desktop\Tuya\venv\lib\site-packages\goto.py", line 175, in _patch_code
    return _make_code(code, buf.tostring())
AttributeError: 'array.array' object has no attribute 'tostring'
```
I got this error using Python 3.9

**Comment by twizt3dkitty** [comment]
This can be fixed by changing line 54 to return code.replace(co_code=codestring)  This is the return value of the _make_code function.  After that, go to line 175 and change it to read return _make_code(code, buf.tobytes())  This will fix this module to work with current versions of python.  Tested to 3.9.6

**Comment by Tribunny** [comment]
> This can be fixed by changing line 54 to return code.replace(co_code=codestring) This is the return value of the _make_code function. After that, go to line 175 and change it to read return _make_code(code, buf.tobytes()) This will fix this module to work with current versions of python. Tested to 3.9.6

I get it,

**Comment by JosephMatan83** [comment]
Does this issue was fixed ?
I'm running `goto-statement==1.2` and I'm getting this error.

**Comment by nic-obert** [comment]
I'm running `goto-statement==1.2` with Python 3.10.5 and I still get this issue.

**Comment by ahopelesshadow** [comment]
> I'm running `goto-statement==1.2` with Python 3.10.5 and I still get this issue.

Make the manual fix twizt3dkitty posted above, i dont think this has been updated past 3.7 or 3.8, i forget, but i no longer have need for this module so i never tested if anything else broke in 3.10.x. the person that opened this issue closed it, not module auther...  im pretty sure this is dead.

**Comment by Cooooldwind** [comment]
Errr... Is this issue fixed? I still have the same problem. Using Python 3.11.1 and `goto-statement==1.2`

**Comment by stonebeaver** [comment]
# Update 2024-11-07

When you `pip install goto-statement` you (still) get version 1.2 which has the bug.
In *goto.py* change line 53 from
```python
    return types.CodeType(*args)
```
to
```python
    return code.replace(co_code=codestring) 
```
and line 175 from
```python
    return _make_code(code, buf.tostring())
```
to
```python
    return _make_code(code, buf.tobytes())
```

If I could reopen this issue, I would. Does anyone see any chance that we get a version 1.3 to pypi?
